-- Source-backed enrichment for the medicines2 catalog.
-- Core rules:
--   * medicines2 IDs, Egyptian prices, barcodes, codes, and inventory boundaries remain authoritative.
--   * medicines3 (EgyptDwa) may contribute Egyptian category, image, popularity, source URL, and observed-price evidence.
--   * medicines4 (Netmeds) is an international reference. INR prices never replace Egyptian catalog prices.
--   * Only verified product-level matches are exposed through the enriched catalog.
--   * Raw source tables remain private and their long-form content is never exposed.

create extension if not exists pg_trgm;

create or replace function public.normalize_catalog_name(value text)
returns text
language sql
immutable
parallel safe
set search_path = public
as $$
  select regexp_replace(
    lower(translate(coalesce(value, ''), 'أإآٱةىؤئًٌٍَُِّْـ', 'ااااهيوي')),
    '[^a-z0-9ء-ي]+',
    '',
    'g'
  );
$$;

create or replace function public.normalize_ascii_catalog_name(value text)
returns text
language sql
immutable
parallel safe
set search_path = public
as $$
  select regexp_replace(lower(coalesce(value, '')), '[^a-z0-9]+', '', 'g');
$$;

create or replace function public.catalog_number_signature(value text)
returns text
language sql
immutable
parallel safe
set search_path = public
as $$
  select regexp_replace(coalesce(value, ''), '[^0-9]+', '', 'g');
$$;

create or replace function public.canonical_source_url(value text)
returns text
language sql
immutable
parallel safe
set search_path = public
as $$
  select nullif(split_part(trim(coalesce(value, '')), ' ', 1), '');
$$;

create or replace function public.clean_netmeds_generic(value text)
returns text
language sql
immutable
parallel safe
set search_path = public
as $$
  select nullif(trim(
    regexp_replace(
      regexp_replace(coalesce(value, ''), '^\s*Generic Name\s*', '', 'i'),
      '\s+Also Known As:.*$',
      '',
      'i'
    )
  ), '');
$$;

create table if not exists public.medicine_catalog_source_evidence (
  id bigint generated by default as identity primary key,
  source_system text not null check (source_system in ('egyptdwa', 'netmeds')),
  source_key text not null,
  medicines2_id bigint not null references public.medicines2(id) on delete cascade,
  match_method text not null,
  confidence text not null default 'verified' check (confidence in ('verified', 'review_required', 'rejected')),
  match_score numeric(6,5),
  source_name text,
  source_url text,
  image_url text,
  category_name text,
  category_url text,
  product_views bigint,
  category_views bigint,
  observed_price numeric(18,3),
  observed_price_text text,
  observed_currency text,
  generic_name text,
  disease_area text,
  prescription_required text,
  manufacturer_name text,
  manufacturer_origin text,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_system, source_key),
  unique (source_system, medicines2_id)
);

comment on table public.medicine_catalog_source_evidence is
  'Verified, source-attributed evidence linked to medicines2 without changing source catalog identity or price.';
comment on column public.medicine_catalog_source_evidence.observed_price is
  'Source-observed value only. It never overrides medicines2.price.';

create index if not exists medicine_catalog_source_evidence_product_idx
  on public.medicine_catalog_source_evidence(medicines2_id, source_system)
  where confidence = 'verified';
create index if not exists medicine_catalog_source_evidence_source_idx
  on public.medicine_catalog_source_evidence(source_system, confidence);

alter table public.medicine_catalog_source_evidence enable row level security;
drop policy if exists medicine_catalog_source_evidence_public_read on public.medicine_catalog_source_evidence;
create policy medicine_catalog_source_evidence_public_read
on public.medicine_catalog_source_evidence
for select
to anon, authenticated
using (confidence = 'verified');

revoke all privileges on table public.medicine_catalog_source_evidence from anon, authenticated;
grant select on public.medicine_catalog_source_evidence to anon, authenticated;

-- Keep the raw imported datasets private. In particular, medicines4 contains
-- long-form third-party content and foreign-market price strings that are not
-- suitable as direct application data.
alter table public.medicines3 enable row level security;
alter table public.medicines4 enable row level security;
revoke all privileges on table public.medicines3 from anon, authenticated;
revoke all privileges on table public.medicines4 from anon, authenticated;

-- EgyptDwa tier 1: normalized full name is unique in both datasets.
with source_rows as (
  select
    "Medicine Name" as source_key,
    public.normalize_catalog_name("Medicine Name") as norm,
    "Price"::numeric as source_price,
    "Category title" as category_name,
    "Category link" as category_url,
    "Views" as product_views,
    "Category views" as category_views,
    "Image" as image_url,
    public.canonical_source_url("Medicine Name link") as source_url
  from public.medicines3
), source_unique as (
  select norm, min(source_key) as source_key
  from source_rows
  where length(norm) >= 5 and norm ~ '[a-zء-ي]'
  group by norm
  having count(*) = 1
), target_rows as (
  select id, public.normalize_catalog_name(name_ar) as norm
  from public.medicines2
  where coalesce(active, true) = true
), target_unique as (
  select norm, min(id) as medicines2_id
  from target_rows
  where length(norm) >= 5 and norm ~ '[a-zء-ي]'
  group by norm
  having count(*) = 1
)
insert into public.medicine_catalog_source_evidence (
  source_system, source_key, medicines2_id, match_method, confidence, match_score,
  source_name, source_url, image_url, category_name, category_url,
  product_views, category_views, observed_price, observed_price_text, observed_currency,
  evidence
)
select
  'egyptdwa', s.source_key, t.medicines2_id,
  'unicode_normalized_name_unique', 'verified', 1.0,
  s.source_key, s.source_url, s.image_url, s.category_name, s.category_url,
  s.product_views, s.category_views, s.source_price, s.source_price::text, 'EGP',
  jsonb_build_object('name_normalization', 'unicode_preserving')
from source_rows s
join source_unique su on su.norm = s.norm and su.source_key = s.source_key
join target_unique t using (norm)
on conflict (source_system, source_key) do nothing;

-- EgyptDwa tier 2: exact normalized name has multiple catalog candidates,
-- but exactly one candidate has the same Egyptian observed price.
with source_rows as (
  select
    "Medicine Name" as source_key,
    public.normalize_catalog_name("Medicine Name") as norm,
    "Price"::numeric as source_price,
    "Category title" as category_name,
    "Category link" as category_url,
    "Views" as product_views,
    "Category views" as category_views,
    "Image" as image_url,
    public.canonical_source_url("Medicine Name link") as source_url
  from public.medicines3
), candidates as (
  select
    s.*,
    m.id as medicines2_id,
    count(*) filter (
      where s.source_price is not null
        and m.price is not null
        and abs(s.source_price - m.price) <= 0.01
    ) over (partition by s.source_key) as matching_price_candidates
  from source_rows s
  join public.medicines2 m
    on public.normalize_catalog_name(m.name_ar) = s.norm
   and coalesce(m.active, true) = true
  where length(s.norm) >= 5 and s.norm ~ '[a-zء-ي]'
)
insert into public.medicine_catalog_source_evidence (
  source_system, source_key, medicines2_id, match_method, confidence, match_score,
  source_name, source_url, image_url, category_name, category_url,
  product_views, category_views, observed_price, observed_price_text, observed_currency,
  evidence
)
select
  'egyptdwa', c.source_key, c.medicines2_id,
  'unicode_normalized_name_exact_price_unique', 'verified', 0.99,
  c.source_key, c.source_url, c.image_url, c.category_name, c.category_url,
  c.product_views, c.category_views, c.source_price, c.source_price::text, 'EGP',
  jsonb_build_object('price_tolerance', 0.01)
from candidates c
where c.matching_price_candidates = 1
  and c.source_price is not null
  and exists (
    select 1 from public.medicines2 m
    where m.id = c.medicines2_id
      and m.price is not null
      and abs(c.source_price - m.price) <= 0.01
  )
on conflict do nothing;

-- EgyptDwa tier 3: conservative spelling variation. A candidate must have:
--   * the same price,
--   * the same complete numeric signature (strength/pack numbers),
--   * trigram similarity >= 0.90,
--   * at least 0.08 separation from the second-best candidate.
with source_rows as (
  select
    "Medicine Name" as source_key,
    "Price"::numeric as source_price,
    public.catalog_number_signature("Medicine Name") as number_signature,
    "Category title" as category_name,
    "Category link" as category_url,
    "Views" as product_views,
    "Category views" as category_views,
    "Image" as image_url,
    public.canonical_source_url("Medicine Name link") as source_url
  from public.medicines3
  where "Medicine Name" is not null
), ranked as (
  select
    s.*,
    candidate.id as medicines2_id,
    candidate.similarity_score,
    row_number() over (
      partition by s.source_key
      order by candidate.similarity_score desc, candidate.id
    ) as candidate_rank
  from source_rows s
  cross join lateral (
    select
      m.id,
      similarity(m.name_ar, s.source_key) as similarity_score
    from public.medicines2 m
    where coalesce(m.active, true) = true
      and s.number_signature <> ''
      and public.catalog_number_signature(m.name_ar) = s.number_signature
      and s.source_price is not null
      and m.price is not null
      and abs(s.source_price - m.price) <= 0.01
      and m.name_ar % s.source_key
    order by similarity(m.name_ar, s.source_key) desc, m.id
    limit 2
  ) candidate
), compared as (
  select
    ranked.*,
    max(similarity_score) filter (where candidate_rank = 2)
      over (partition by source_key) as second_similarity
  from ranked
)
insert into public.medicine_catalog_source_evidence (
  source_system, source_key, medicines2_id, match_method, confidence, match_score,
  source_name, source_url, image_url, category_name, category_url,
  product_views, category_views, observed_price, observed_price_text, observed_currency,
  evidence
)
select
  'egyptdwa', c.source_key, c.medicines2_id,
  'arabic_trigram_price_numbers', 'verified', c.similarity_score,
  c.source_key, c.source_url, c.image_url, c.category_name, c.category_url,
  c.product_views, c.category_views, c.source_price, c.source_price::text, 'EGP',
  jsonb_build_object(
    'number_signature', c.number_signature,
    'second_similarity', coalesce(c.second_similarity, 0),
    'minimum_similarity', 0.90,
    'minimum_margin', 0.08
  )
from compared c
where c.candidate_rank = 1
  and c.similarity_score >= 0.90
  and c.similarity_score - coalesce(c.second_similarity, 0) >= 0.08
on conflict do nothing;

-- Netmeds product-level evidence is accepted only for unique normalized English
-- names on both sides. Foreign price strings are retained as evidence only.
with source_rows as (
  select
    med_name as source_key,
    public.normalize_ascii_catalog_name(med_name) as norm,
    med_url as source_url,
    public.canonical_source_url(img_urls) as image_url,
    public.clean_netmeds_generic(generic_name) as generic_name,
    regexp_replace(coalesce(disease_name, ''), '\s*\([0-9,]+\)\s*$', '', 'g') as disease_area,
    prescription_required,
    nullif(trim(regexp_replace(coalesce(drug_manufacturer, ''), '^\s*\*?\s*Mkt:\s*', '', 'i')), '') as manufacturer_name,
    nullif(trim(regexp_replace(coalesce(drug_manufacturer_origin, ''), '^\s*\*?\s*Country of Origin:\s*', '', 'i')), '') as manufacturer_origin,
    final_price as observed_price_text
  from public.medicines4
), source_unique as (
  select norm, min(source_key) as source_key
  from source_rows
  where length(norm) >= 6 and norm ~ '[a-z]'
  group by norm
  having count(*) = 1
), target_rows as (
  select id, public.normalize_ascii_catalog_name(name_en) as norm
  from public.medicines2
  where coalesce(active, true) = true
), target_unique as (
  select norm, min(id) as medicines2_id
  from target_rows
  where length(norm) >= 6 and norm ~ '[a-z]'
  group by norm
  having count(*) = 1
)
insert into public.medicine_catalog_source_evidence (
  source_system, source_key, medicines2_id, match_method, confidence, match_score,
  source_name, source_url, image_url, observed_price_text, observed_currency,
  generic_name, disease_area, prescription_required, manufacturer_name,
  manufacturer_origin, evidence
)
select
  'netmeds', s.source_key, t.medicines2_id,
  'ascii_normalized_name_unique', 'verified', 1.0,
  s.source_key, s.source_url, s.image_url, s.observed_price_text, 'INR',
  s.generic_name, nullif(s.disease_area, ''), s.prescription_required,
  s.manufacturer_name, s.manufacturer_origin,
  jsonb_build_object(
    'market', 'India',
    'price_policy', 'reference_only_never_overwrite_egyptian_price'
  )
from source_rows s
join source_unique su on su.norm = s.norm and su.source_key = s.source_key
join target_unique t using (norm)
on conflict do nothing;

-- Standalone international ingredient reference. This connects the platform to
-- medicines4 knowledge without claiming that Indian brands equal Egyptian brands.
create table if not exists public.international_ingredient_reference (
  ingredient_key text primary key,
  ingredient_name text not null,
  source_system text not null default 'netmeds' check (source_system = 'netmeds'),
  source_product_count bigint not null,
  disease_areas text[] not null default '{}',
  prescription_required_observed boolean not null default false,
  manufacturer_sample text,
  manufacturer_origin_sample text,
  source_url_sample text,
  updated_at timestamptz not null default now()
);

alter table public.international_ingredient_reference enable row level security;
drop policy if exists international_ingredient_reference_public_read on public.international_ingredient_reference;
create policy international_ingredient_reference_public_read
on public.international_ingredient_reference
for select
to anon, authenticated
using (true);
revoke all privileges on table public.international_ingredient_reference from anon, authenticated;
grant select on public.international_ingredient_reference to anon, authenticated;

with source_parts as (
  select
    m.med_name,
    m.med_url,
    trim(regexp_replace(part, '\s+[0-9].*$', '', 'i')) as ingredient_name,
    regexp_replace(coalesce(m.disease_name, ''), '\s*\([0-9,]+\)\s*$', '', 'g') as disease_area,
    m.prescription_required,
    nullif(trim(regexp_replace(coalesce(m.drug_manufacturer, ''), '^\s*\*?\s*Mkt:\s*', '', 'i')), '') as manufacturer_name,
    nullif(trim(regexp_replace(coalesce(m.drug_manufacturer_origin, ''), '^\s*\*?\s*Country of Origin:\s*', '', 'i')), '') as manufacturer_origin
  from public.medicines4 m
  cross join lateral regexp_split_to_table(
    coalesce(public.clean_netmeds_generic(m.generic_name), ''),
    '\+'
  ) part
), cleaned as (
  select
    public.normalize_ascii_catalog_name(ingredient_name) as ingredient_key,
    ingredient_name,
    med_name,
    med_url,
    nullif(disease_area, '') as disease_area,
    prescription_required,
    manufacturer_name,
    manufacturer_origin
  from source_parts
  where length(trim(ingredient_name)) >= 3
    and public.normalize_ascii_catalog_name(ingredient_name) <> ''
), aggregated as (
  select
    ingredient_key,
    min(ingredient_name) as ingredient_name,
    count(distinct med_name)::bigint as source_product_count,
    coalesce(array_agg(distinct disease_area) filter (where disease_area is not null), '{}') as disease_areas,
    bool_or(lower(coalesce(prescription_required, '')) like '%rx%') as prescription_required_observed,
    min(manufacturer_name) filter (where manufacturer_name is not null) as manufacturer_sample,
    min(manufacturer_origin) filter (where manufacturer_origin is not null) as manufacturer_origin_sample,
    min(med_url) filter (where med_url is not null) as source_url_sample
  from cleaned
  group by ingredient_key
)
insert into public.international_ingredient_reference (
  ingredient_key, ingredient_name, source_product_count, disease_areas,
  prescription_required_observed, manufacturer_sample,
  manufacturer_origin_sample, source_url_sample, updated_at
)
select
  ingredient_key, ingredient_name, source_product_count, disease_areas,
  prescription_required_observed, manufacturer_sample,
  manufacturer_origin_sample, source_url_sample, now()
from aggregated
on conflict (ingredient_key) do update set
  ingredient_name = excluded.ingredient_name,
  source_product_count = excluded.source_product_count,
  disease_areas = excluded.disease_areas,
  prescription_required_observed = excluded.prescription_required_observed,
  manufacturer_sample = excluded.manufacturer_sample,
  manufacturer_origin_sample = excluded.manufacturer_origin_sample,
  source_url_sample = excluded.source_url_sample,
  updated_at = now();

create or replace view public.medicines_catalog_enriched_v1
with (security_invoker = true)
as
select
  catalog.*,
  coalesce(catalog.category, egyptdwa.category_name) as display_category,
  egyptdwa.category_name as egyptdwa_category,
  egyptdwa.category_url as egyptdwa_category_url,
  egyptdwa.image_url as egyptdwa_image_url,
  egyptdwa.source_url as egyptdwa_source_url,
  egyptdwa.product_views as egyptdwa_product_views,
  egyptdwa.category_views as egyptdwa_category_views,
  egyptdwa.observed_price as egyptdwa_observed_price,
  egyptdwa.observed_currency as egyptdwa_observed_currency,
  egyptdwa.match_method as egyptdwa_match_method,
  egyptdwa.match_score as egyptdwa_match_score,
  netmeds.generic_name as international_generic_name,
  netmeds.disease_area as international_disease_area,
  netmeds.prescription_required as international_prescription_signal,
  netmeds.manufacturer_name as international_manufacturer,
  netmeds.manufacturer_origin as international_manufacturer_origin,
  netmeds.source_url as international_source_url,
  netmeds.image_url as international_image_url,
  netmeds.observed_price_text as international_observed_price_text,
  netmeds.observed_currency as international_observed_currency,
  netmeds.match_method as international_match_method,
  netmeds.match_score as international_match_score,
  ((egyptdwa.id is not null)::integer + (netmeds.id is not null)::integer) as enrichment_source_count
from public.medicines_catalog catalog
left join public.medicine_catalog_source_evidence egyptdwa
  on egyptdwa.medicines2_id = catalog.id
 and egyptdwa.source_system = 'egyptdwa'
 and egyptdwa.confidence = 'verified'
left join public.medicine_catalog_source_evidence netmeds
  on netmeds.medicines2_id = catalog.id
 and netmeds.source_system = 'netmeds'
 and netmeds.confidence = 'verified';

grant select on public.medicines_catalog_enriched_v1 to anon, authenticated;

create or replace view public.medicines_catalog_metrics
with (security_invoker = true)
as
select
  count(*)::bigint as total_active,
  count(*) filter (where dosage_form is not null)::bigint as with_dosage_form,
  count(*) filter (where strength is not null)::bigint as with_strength,
  count(*) filter (where barcode is not null)::bigint as with_barcode,
  count(*) filter (where price is not null)::bigint as with_price,
  count(*) filter (where legacy_medicine_id is not null)::bigint as with_legacy_compatibility,
  count(*) filter (where egyptdwa_source_url is not null)::bigint as with_egyptdwa_evidence,
  count(*) filter (where international_source_url is not null)::bigint as with_international_product_evidence,
  (select count(*) from public.international_ingredient_reference)::bigint as international_ingredient_references
from public.medicines_catalog_enriched_v1;

grant select on public.medicines_catalog_metrics to anon, authenticated;

-- Search candidates against indexed base columns first, then join the enriched
-- view only for the small result set. This avoids scanning the full joined view.
create or replace function public.search_medicines_catalog(
  p_query text,
  p_limit integer default 50
)
returns setof public.medicines_catalog_enriched_v1
language sql
stable
security invoker
set search_path = public
as $$
  with input as (
    select trim(coalesce(p_query, '')) as query,
           greatest(1, least(coalesce(p_limit, 50), 100)) as row_limit
  ), candidates as (
    select m.id, 2000::numeric as score
    from public.medicines2 m, input i
    where i.query <> ''
      and coalesce(m.active, true) = true
      and (m.barcode = i.query or m.code = i.query or m.custom_product_code = i.query)

    union all

    select m.id, (1000 + similarity(m.name_en, i.query) * 100)::numeric as score
    from public.medicines2 m, input i
    where length(i.query) >= 2
      and coalesce(m.active, true) = true
      and m.name_en is not null
      and (m.name_en % i.query or m.name_en ilike '%' || i.query || '%')

    union all

    select m.id, (1000 + similarity(m.name_ar, i.query) * 100)::numeric as score
    from public.medicines2 m, input i
    where length(i.query) >= 2
      and coalesce(m.active, true) = true
      and m.name_ar is not null
      and (m.name_ar % i.query or m.name_ar ilike '%' || i.query || '%')

    union all

    select m.id, 700::numeric as score
    from public.medicines2 m, input i
    where length(i.query) >= 2
      and coalesce(m.active, true) = true
      and (m.barcode ilike '%' || i.query || '%' or m.code ilike '%' || i.query || '%')

    union all

    select m.id, 1::numeric as score
    from public.medicines2 m, input i
    where i.query = '' and coalesce(m.active, true) = true
  ), ranked as (
    select c.id, max(c.score) as score
    from candidates c
    group by c.id
    order by max(c.score) desc, c.id
    limit (select row_limit from input)
  )
  select enriched.*
  from ranked
  join public.medicines_catalog_enriched_v1 enriched on enriched.id = ranked.id
  order by ranked.score desc, coalesce(enriched.name_en, enriched.name_ar), enriched.id;
$$;

revoke all on function public.search_medicines_catalog(text, integer) from public;
grant execute on function public.search_medicines_catalog(text, integer) to anon, authenticated;

create or replace function public.search_medicines_catalog_index(
  p_query text,
  p_limit integer default 60
)
returns table (
  entity_type text,
  entity_key text,
  title text,
  subtitle text,
  href text,
  category text,
  weight numeric
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    'catalog_product'::text,
    product.id::text,
    coalesce(nullif(product.name_en, ''), nullif(product.name_ar, ''), 'Product #' || product.id::text),
    concat_ws(
      ' · ',
      nullif(product.name_ar, ''),
      product.barcode,
      product.code,
      case when product.price is not null then product.price::text || ' EGP' end,
      product.display_category
    ),
    '/catalog/' || product.id::text,
    coalesce(product.display_category, 'medicine catalog'),
    (case when product.barcode is not null then 30 else 20 end
      + case when product.enrichment_source_count > 0 then 5 else 0 end)::numeric
  from public.search_medicines_catalog(p_query, p_limit) product;
$$;

revoke all on function public.search_medicines_catalog_index(text, integer) from public;
grant execute on function public.search_medicines_catalog_index(text, integer) to anon, authenticated;

create or replace function public.resolve_legacy_medicine_catalog(
  p_legacy_medicine_id integer
)
returns setof public.medicines_catalog_enriched_v1
language sql
stable
security invoker
set search_path = public
as $$
  select product.*
  from public.medicines_catalog_enriched_v1 product
  where product.legacy_medicine_id = p_legacy_medicine_id
  limit 1;
$$;

revoke all on function public.resolve_legacy_medicine_catalog(integer) from public;
grant execute on function public.resolve_legacy_medicine_catalog(integer) to anon, authenticated;

create or replace view public.medicine_catalog_enrichment_metrics
with (security_invoker = true)
as
select
  count(*) filter (where source_system = 'egyptdwa' and confidence = 'verified')::bigint as verified_egyptdwa_products,
  count(*) filter (where source_system = 'netmeds' and confidence = 'verified')::bigint as verified_netmeds_products,
  count(*) filter (where confidence = 'review_required')::bigint as review_required_products,
  (select count(*) from public.international_ingredient_reference)::bigint as international_ingredient_references,
  max(updated_at) as latest_evidence_update
from public.medicine_catalog_source_evidence;

grant select on public.medicine_catalog_enrichment_metrics to anon, authenticated;
