import { useEffect, useState } from "react";
import { AlertCircle, Check, MessageCircle, RefreshCw, ShieldAlert, X } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { usePatientAuth } from "@/lib/patient-auth";

type Profile={role:string;is_active:boolean};
type Comment={id:string;entity_type:string;entity_key:string;body:string;is_anonymous:boolean;status:string;created_at:string};
type Experience={id:string;canonical_id:number;report_type:string;title:string;description:string;severity:string;evidence_urls:string[];status:string;emergency_acknowledged:boolean;created_at:string};
type CompanyMessage={id:string;company_slug:string;sender_name:string;subject:string;body:string;status:string;created_at:string};
const humanize=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());

export default function AdminCommunity(){
  const {session,supabaseFetch}=usePatientAuth();const [profile,setProfile]=useState<Profile|null>(null);const [comments,setComments]=useState<Comment[]>([]);const [reports,setReports]=useState<Experience[]>([]);const [messages,setMessages]=useState<CompanyMessage[]>([]);const [notes,setNotes]=useState<Record<string,string>>({});const [loading,setLoading]=useState(true);const [saving,setSaving]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);
  const isAdmin=Boolean(profile?.is_active&&["admin","platform_admin","super_admin"].includes(profile.role));
  async function load(){setLoading(true);setError(null);try{if(!session?.user?.id)throw new Error("Sign in through the staff portal first.");const [profiles,commentRows,reportRows,messageRows]=await Promise.all([
    supabaseFetch<Profile[]>(`/rest/v1/profiles?select=role,is_active&id=eq.${session.user.id}&limit=1`),
    supabaseFetch<Comment[]>("/rest/v1/entity_comments?select=id,entity_type,entity_key,body,is_anonymous,status,created_at&status=in.(pending,approved,hidden)&order=created_at.asc&limit=300"),
    supabaseFetch<Experience[]>("/rest/v1/medicine_experience_reports?select=id,canonical_id,report_type,title,description,severity,evidence_urls,status,emergency_acknowledged,created_at&status=in.(submitted,under_review,escalated,approved)&order=created_at.asc&limit=300"),
    supabaseFetch<CompanyMessage[]>("/rest/v1/company_profile_messages?select=id,company_slug,sender_name,subject,body,status,created_at&status=in.(unread,read,replied)&order=created_at.asc&limit=300"),
  ]);const next=profiles[0]||null;setProfile(next);if(!next?.is_active||!["admin","platform_admin","super_admin"].includes(next.role))throw new Error("Platform-admin access is required.");setComments(commentRows);setReports(reportRows);setMessages(messageRows);}catch(cause){setError(cause instanceof Error?cause.message:"Could not load moderation queues.");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[session?.user?.id]);
  async function reviewComment(row:Comment,status:"approved"|"rejected"|"hidden"){if(!session?.user?.id)return;setSaving(row.id);try{await supabaseFetch(`/rest/v1/entity_comments?id=eq.${row.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status,moderation_notes:notes[row.id]?.trim()||null,reviewed_by:session.user.id,reviewed_at:new Date().toISOString()})});setMessage(`Comment ${status}.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Comment review failed.");}finally{setSaving(null);}}
  async function reviewReport(row:Experience,status:"approved"|"rejected"|"escalated"){if(!session?.user?.id)return;setSaving(row.id);try{await supabaseFetch(`/rest/v1/medicine_experience_reports?id=eq.${row.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status,moderation_notes:notes[row.id]?.trim()||null,reviewed_by:session.user.id,reviewed_at:new Date().toISOString()})});setMessage(`Medicine experience report ${status}.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Report review failed.");}finally{setSaving(null);}}
  async function updateMessage(row:CompanyMessage,status:string){setSaving(row.id);try{await supabaseFetch(`/rest/v1/company_profile_messages?id=eq.${row.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status})});setMessage(`Company message marked ${status}.`);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Message update failed.");}finally{setSaving(null);}}
  return <main className="container mx-auto max-w-7xl px-4 py-8"><section className="rounded-3xl border bg-card p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-semibold uppercase tracking-wide text-muted-foreground"><ShieldAlert className="h-4 w-4"/>Community safety operations</p><h1 className="mt-3 text-3xl font-bold">Comments, medicine reports, and company inbox</h1><p className="mt-3 max-w-4xl text-muted-foreground">Approve useful comments, prevent unsupported medical claims, escalate serious medicine experiences, and route private company messages. Approval means suitable for display—not clinical validation or causal confirmation.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div></section>{error&&<Alert variant="destructive" className="mt-5"><AlertCircle className="h-4 w-4"/><AlertDescription>{error}</AlertDescription></Alert>}{message&&<Alert className="mt-5"><AlertDescription>{message}</AlertDescription></Alert>}
  {!loading&&isAdmin&&<><Queue title={`Comments (${comments.filter(row=>row.status==="pending").length} pending)`}>{comments.map(row=><Card key={row.id}><CardHeader><div className="flex items-start justify-between gap-3"><CardTitle className="text-lg">{humanize(row.entity_type)} · {row.entity_key}</CardTitle><Badge variant="outline">{humanize(row.status)}</Badge></div></CardHeader><CardContent className="space-y-3"><p className="whitespace-pre-wrap text-sm leading-6">{row.body}</p><Textarea value={notes[row.id]||""} onChange={event=>setNotes(current=>({...current,[row.id]:event.target.value}))} placeholder="Moderation rationale"/><div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>void reviewComment(row,"approved")} disabled={saving===row.id}><Check className="mr-1 h-4 w-4"/>Approve</Button><Button size="sm" variant="outline" onClick={()=>void reviewComment(row,"hidden")} disabled={saving===row.id}>Hide</Button><Button size="sm" variant="destructive" onClick={()=>void reviewComment(row,"rejected")} disabled={saving===row.id}><X className="mr-1 h-4 w-4"/>Reject</Button></div></CardContent></Card>)}</Queue>
  <Queue title={`Medicine experience reports (${reports.filter(row=>["submitted","under_review","escalated"].includes(row.status)).length} active)`}>{reports.map(row=><Card key={row.id} className={row.severity==="serious"?"border-destructive/50":""}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-lg"><a href={`/catalog/${row.canonical_id}`} className="text-primary">#{row.canonical_id}</a> · {row.title}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{humanize(row.report_type)}</p></div><Badge variant={row.severity==="serious"?"destructive":"outline"}>{humanize(row.severity)}</Badge></div></CardHeader><CardContent className="space-y-3"><p className="whitespace-pre-wrap text-sm leading-6">{row.description}</p>{row.evidence_urls.map(url=><a key={url} href={url} target="_blank" rel="noreferrer" className="block break-all text-sm font-semibold text-primary">{url}</a>)}<Textarea value={notes[row.id]||""} onChange={event=>setNotes(current=>({...current,[row.id]:event.target.value}))} placeholder="Safety review notes"/><div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>void reviewReport(row,"approved")} disabled={saving===row.id}>Approve anonymized display</Button><Button size="sm" variant="outline" onClick={()=>void reviewReport(row,"escalated")} disabled={saving===row.id}>Escalate</Button><Button size="sm" variant="destructive" onClick={()=>void reviewReport(row,"rejected")} disabled={saving===row.id}>Reject</Button></div></CardContent></Card>)}</Queue>
  <Queue title={`Company messages (${messages.filter(row=>row.status==="unread").length} unread)`}>{messages.map(row=><Card key={row.id}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-lg"><a href={`/companies/${encodeURIComponent(row.company_slug)}`} className="text-primary">{row.company_slug}</a> · {row.subject}</CardTitle><p className="mt-1 text-sm text-muted-foreground">From {row.sender_name}</p></div><Badge variant="outline">{row.status}</Badge></div></CardHeader><CardContent className="space-y-3"><p className="whitespace-pre-wrap text-sm leading-6">{row.body}</p><div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>void updateMessage(row,"read")} disabled={saving===row.id}>Mark read</Button><Button size="sm" variant="outline" onClick={()=>void updateMessage(row,"replied")} disabled={saving===row.id}>Mark replied</Button><Button size="sm" variant="outline" onClick={()=>void updateMessage(row,"closed")} disabled={saving===row.id}>Close</Button></div></CardContent></Card>)}</Queue></>}</main>;
}
function Queue({title,children}:{title:string;children:React.ReactNode}){const has=Array.isArray(children)?children.length>0:Boolean(children);return <section className="mt-8"><h2 className="flex items-center gap-2 text-2xl font-semibold"><MessageCircle className="h-5 w-5"/>{title}</h2><div className="mt-4 grid gap-4 xl:grid-cols-2">{has?children:<Card><CardContent className="p-6 text-sm text-muted-foreground">No items in this queue.</CardContent></Card>}</div></section>;}
