import { useEffect, useMemo, useState } from "react";
import { BadgeCheck, Building2, Database, Network, RefreshCw, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ConnectedNextActions } from "@/components/connected-next-actions";
import { Input } from "@/components/ui/input";
import { useLanguage } from "@/lib/i18n";
import { usePatientAuth } from "@/lib/patient-auth";
import { seoEntityPath } from "@/lib/seo-entities";

type GeneratedCompany={company_slug:string;company_name:string;product_count:number;generic_count:number;drug_class_count:number;route_count:number;products_with_images:number;products_with_price_history:number;products_with_marketplace_offers:number;min_price_egp:number|null;max_price_egp:number|null;leading_generics:string[];leading_classes:string[];leading_routes:string[];portfolio_sample_ids:number[];portfolio_sample_names:string[];source_name:string;generated_at:string};
type OfficialCompany={company_slug:string;display_name:string;company_type:string;description:string|null;logo_url:string|null;country:string|null;city:string|null;therapeutic_areas:string[]|null;product_categories:string[]|null;capabilities:string[]|null;verification_status:string};
const values=(value:string[]|null|undefined)=>Array.isArray(value)?value.filter(Boolean):[];
const humanize=(value:string|null|undefined)=>String(value||"Healthcare company").replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());

export default function CompanyProfiles(){
  const {t}=useLanguage();const {supabaseFetch}=usePatientAuth();const [query,setQuery]=useState("");const [companies,setCompanies]=useState<GeneratedCompany[]>([]);const [official,setOfficial]=useState<Record<string,OfficialCompany>>({});const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);
  async function load(){setLoading(true);setError(null);try{const [generatedRows,officialRows]=await Promise.all([
    supabaseFetch<GeneratedCompany[]>("/rest/v1/medicine_manufacturer_profiles_generated?select=*&order=product_count.desc,company_name.asc&limit=5000"),
    supabaseFetch<OfficialCompany[]>("/rest/v1/industry_company_profiles?select=company_slug,display_name,company_type,description,logo_url,country,city,therapeutic_areas,product_categories,capabilities,verification_status&verification_status=eq.verified&is_public=eq.true&limit=1000"),
  ]);const officialMap=Object.fromEntries(officialRows.map(profile=>[profile.company_slug,profile]));const generatedBySlug=new Map(generatedRows.map(row=>[row.company_slug,row]));for(const profile of officialRows){if(!generatedBySlug.has(profile.company_slug))generatedRows.push({company_slug:profile.company_slug,company_name:profile.display_name,product_count:0,generic_count:0,drug_class_count:0,route_count:0,products_with_images:0,products_with_price_history:0,products_with_marketplace_offers:0,min_price_egp:null,max_price_egp:null,leading_generics:[],leading_classes:[],leading_routes:[],portfolio_sample_ids:[],portfolio_sample_names:[],source_name:"Official company profile",generated_at:new Date().toISOString()});}setCompanies(generatedRows.sort((a,b)=>b.product_count-a.product_count||a.company_name.localeCompare(b.company_name)));setOfficial(officialMap);}catch(cause){setError(cause instanceof Error?cause.message:t("Could not load company profiles.","تعذر تحميل ملفات الشركات."));}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  const filtered=useMemo(()=>{const normalized=query.trim().toLocaleLowerCase();if(!normalized)return companies;return companies.filter(company=>{const profile=official[company.company_slug];return[company.company_name,profile?.display_name,profile?.company_type,profile?.description,profile?.country,profile?.city,...company.leading_generics,...company.leading_classes,...company.leading_routes,...company.portfolio_sample_names,...values(profile?.therapeutic_areas),...values(profile?.product_categories),...values(profile?.capabilities)].filter(Boolean).join(" ").toLocaleLowerCase().includes(normalized);});},[companies,official,query]);
  const totals=useMemo(()=>({products:companies.reduce((sum,company)=>sum+Number(company.product_count||0),0),official:companies.filter(company=>Boolean(official[company.company_slug])).length,generics:companies.reduce((sum,company)=>sum+Number(company.generic_count||0),0),marketplace:companies.reduce((sum,company)=>sum+Number(company.products_with_marketplace_offers||0),0)}),[companies,official]);
  return <main className="container mx-auto max-w-7xl px-4 py-8"><section className="rounded-3xl border bg-card p-6 shadow-sm md:p-8"><p className="flex items-center gap-2 text-sm font-medium uppercase tracking-wide text-muted-foreground"><Network className="h-4 w-4"/>{t("Connected healthcare company network","شبكة شركات الرعاية الصحية المترابطة")}</p><div className="mt-3 grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><h1 className="text-3xl font-bold tracking-tight md:text-4xl">{t("Manufacturer profiles generated from the medicine encyclopedia","ملفات الشركات المصنعة المولدة من موسوعة الأدوية")}</h1><p className="mt-3 max-w-4xl text-muted-foreground">{t("Every distinct manufacturer in the canonical medicine encyclopedia receives a connected portfolio page. Verified companies can claim the generated profile and add official information without replacing independent medicine evidence.","يحصل كل مصنع مميز في موسوعة الأدوية الموحدة على صفحة محفظة مترابطة، ويمكن للشركات الموثقة المطالبة بالملف وإضافة معلومات رسمية دون استبدال أدلة الأدوية المستقلة.")}</p></div><a href="/industry" className="inline-flex items-center justify-center rounded-lg bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground"><Building2 className="mr-2 h-4 w-4"/>{t("Create or claim a profile","إنشاء أو المطالبة بملف")}</a></div></section>
  <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label={t("Encyclopedia manufacturers","مصنعو الموسوعة")} value={companies.length}/><Metric label={t("Official verified profiles","الملفات الرسمية الموثقة")} value={totals.official}/><Metric label={t("Canonical portfolio products","منتجات المحفظة الموحدة")} value={totals.products}/><Metric label={t("Marketplace-connected products","منتجات مرتبطة بالسوق")} value={totals.marketplace}/></section><div className="mt-6"><ConnectedNextActions contextType="module" contextKey="companies"/></div>
  <section className="mt-6 flex flex-wrap gap-2"><a href="/industry" className="rounded-lg border border-primary/30 bg-primary/5 px-4 py-2 text-sm font-semibold text-primary">{t("Industry contribution network","شبكة مساهمات الشركات")}</a><a href="/medicines" className="rounded-lg border px-4 py-2 text-sm font-semibold hover:bg-muted">{t("Open medicine search","فتح بحث الأدوية")}</a><a href="/marketplace" className="rounded-lg border px-4 py-2 text-sm font-semibold hover:bg-muted">{t("Open marketplace","فتح السوق")}</a></section>
  <section className="mt-6 rounded-2xl border bg-card p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_auto_auto]"><label className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={query} onChange={event=>setQuery(event.target.value)} placeholder={t("Search manufacturer, medicine, scientific name, class, route, or capability...","ابحث عن مصنع أو دواء أو اسم علمي أو تصنيف أو طريق أو قدرة...")}/></label><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading?"animate-spin":""}`}/>{t("Refresh","تحديث")}</Button><Button variant="outline" onClick={()=>setQuery("")}>{t("Reset","إعادة ضبط")}</Button></div><p className="mt-3 text-sm text-muted-foreground">{filtered.length.toLocaleString()} {t("company profiles","ملف شركة")}</p>{error&&<p className="mt-3 text-sm text-destructive">{error}</p>}</section>
  <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(company=>{const profile=official[company.company_slug];return <Card key={company.company_slug} className={`shadow-sm ${profile?"border-primary/30":""}`}><CardHeader><div className="flex items-start gap-3">{profile?.logo_url&&<img src={profile.logo_url} alt="" className="h-12 w-12 rounded-lg border bg-background object-contain p-1"/>}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><CardTitle className="text-lg leading-7">{profile?.display_name||company.company_name}</CardTitle>{profile&&<Badge className="gap-1"><BadgeCheck className="h-3 w-3"/>{t("Official","رسمي")}</Badge>}</div><p className="text-sm text-muted-foreground">{profile?humanize(profile.company_type):t("Encyclopedia-derived manufacturer","شركة مصنعة مشتقة من الموسوعة")}</p></div></div></CardHeader><CardContent className="space-y-3 text-sm">{profile?.description&&<p className="line-clamp-3 leading-6 text-muted-foreground">{profile.description}</p>}<div className="flex flex-wrap gap-2"><Badge variant="secondary">{company.product_count.toLocaleString()} {t("medicines","دواء")}</Badge><Badge variant="outline">{company.generic_count.toLocaleString()} {t("scientific names","اسم علمي")}</Badge><Badge variant="outline">{company.drug_class_count.toLocaleString()} {t("classes","تصنيف")}</Badge>{company.products_with_marketplace_offers>0&&<Badge variant="outline">{company.products_with_marketplace_offers} {t("market offers","عروض سوق")}</Badge>}</div>{company.leading_generics.length>0&&<Info label={t("Scientific names","الأسماء العلمية")} value={company.leading_generics.slice(0,4).join(", ")}/>} {company.leading_classes.length>0&&<Info label={t("Drug classes","التصنيفات الدوائية")} value={company.leading_classes.slice(0,4).join(", ")}/>} {company.portfolio_sample_names.length>0&&<Info label={t("Portfolio sample","عينة من المحفظة")} value={company.portfolio_sample_names.slice(0,4).join(", ")}/>} {company.min_price_egp!=null&&company.max_price_egp!=null&&<Info label={t("Evidence price range","نطاق سعر الأدلة")} value={`${Number(company.min_price_egp).toLocaleString()}–${Number(company.max_price_egp).toLocaleString()} EGP`}/>}<div className="flex flex-wrap items-center gap-2 pt-1"><a href={seoEntityPath("company",company.company_slug)} className="inline-flex font-semibold text-primary">{t("Open company and canonical portfolio","فتح الشركة والمحفظة الموحدة")}</a><Badge variant="secondary" className="gap-1"><Database className="h-3 w-3"/>{t("Generated from medicines","مولد من الأدوية")}</Badge></div></CardContent></Card>;})}{!loading&&filtered.length===0&&<Card><CardContent className="p-6 text-sm text-muted-foreground">{t("No companies match this search.","لا توجد شركات مطابقة للبحث.")}</CardContent></Card>}</section></main>;
}
function Metric({label,value}:{label:string;value:number|string}){return <Card><CardContent className="p-4"><div className="text-xs text-muted-foreground">{label}</div><div className="text-2xl font-bold">{typeof value==="number"?value.toLocaleString():value}</div></CardContent></Card>;}
function Info({label,value}:{label:string;value:string}){return <div><div className="text-xs text-muted-foreground">{label}</div><div className="font-medium break-words">{value||"—"}</div></div>;}
