import { CheckCircle2, GraduationCap, PlayCircle, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const lessons=[
 {title:"1. Choose the right branch",goal:"Confirm you are entering data for the correct pharmacy branch before doing any accounting work.",steps:["Open Pharmacy Finance, Inventory, or Purchases.","Check the branch selector at the top of the page.","Never enter invoices or expenses under the wrong branch."]},
 {title:"2. Add suppliers",goal:"Create supplier records before entering purchase invoices.",steps:["Open /pharmacy/purchases.","Type the supplier name exactly as it appears on invoices.","Use the same supplier record every time to keep balances accurate."]},
 {title:"3. Add medicines to inventory",goal:"Use the Egyptian medicines catalog as the master source of medicine names.",steps:["Open /pharmacy/inventory.","Search by English name, Arabic name, or barcode.","Select the matching catalog medicine.","Enter batch number, expiry date, quantity, cost, selling price, and reorder level."]},
 {title:"4. Enter supplier purchase invoices",goal:"Record stock received from suppliers and create batch-level inventory.",steps:["Open /pharmacy/purchases.","Choose supplier, invoice number, invoice date, and paid amount.","Select the inventory item.","Enter quantity, unit cost, selling price, batch number, and expiry.","Save the invoice. The system creates a stock batch and audit movement."]},
 {title:"5. Record sales and expenses",goal:"Keep daily profit reports accurate.",steps:["Open /pharmacy/finance.","Record sales as sale entries.","Record rent, salaries, utilities, delivery, and other costs as expense entries.","Use clear categories so reports remain useful."]},
 {title:"6. Review reports before closing",goal:"Catch mistakes before the day ends.",steps:["Review sales, expenses, and profit for the selected period.","Check latest purchase invoices.","Check low-stock and near-expiry alerts.","Report unusual balances to the branch owner."]}
];
const checklist=["Confirm branch before entry","Enter supplier invoices immediately","Use catalog medicine search first","Check batch number and expiry date","Record paid amount accurately","Record daily expenses by category","Review low-stock and near-expiry alerts","Close the day after checking sales, expenses, and profit"];
const voiceover=["Welcome to the pharmacy accountant training. Your job is to keep stock, supplier invoices, sales, expenses, and profit accurate every day.","Start by confirming the correct branch. A wrong branch selection means the reports will be wrong, even if the invoice data is correct.","When adding stock, always search the Egyptian medicines catalog first. This keeps medicine names consistent across branches and reports.","For each purchase invoice, enter the supplier, invoice date, paid amount, quantity, unit cost, selling price, batch number, and expiry date.","The system then creates a stock batch and an audit movement, so the owner can trace where every stock increase came from.","At the end of the day, review sales, expenses, profit, low-stock alerts, and near-expiry medicines before closing."];

export default function PharmacyTraining(){return <div className="container mx-auto max-w-6xl px-4 py-8"><div className="mb-8"><div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Pharmacy learning center</div><h1 className="mt-2 flex items-center gap-2 text-3xl font-bold"><GraduationCap className="h-7 w-7"/>Accountant training</h1><p className="mt-2 max-w-3xl text-muted-foreground">A role-specific onboarding guide for pharmacy accountants using the branch finance, inventory, supplier, and purchase invoice workflows.</p></div><div className="mb-6 grid gap-4 md:grid-cols-3"><Card><CardContent className="p-4"><PlayCircle className="mb-2 h-6 w-6"/><div className="font-semibold">Video-ready</div><p className="text-sm text-muted-foreground">Scene-by-scene content for a short accountant training video.</p></CardContent></Card><Card><CardContent className="p-4"><ShieldCheck className="mb-2 h-6 w-6"/><div className="font-semibold">Operationally safe</div><p className="text-sm text-muted-foreground">Focuses on correct branch, invoice, batch, expiry, and daily closing habits.</p></CardContent></Card><Card><CardContent className="p-4"><CheckCircle2 className="mb-2 h-6 w-6"/><div className="font-semibold">Daily checklist</div><p className="text-sm text-muted-foreground">Simple closing routine to reduce accounting and stock mistakes.</p></CardContent></Card></div><div className="grid gap-6 lg:grid-cols-[2fr_1fr]"><div className="space-y-4">{lessons.map(lesson=><Card key={lesson.title}><CardHeader><div className="flex items-start justify-between gap-3"><CardTitle>{lesson.title}</CardTitle><Badge variant="outline">Lesson</Badge></div><p className="text-sm text-muted-foreground">{lesson.goal}</p></CardHeader><CardContent><ol className="list-decimal space-y-2 pl-5 text-sm">{lesson.steps.map(step=><li key={step}>{step}</li>)}</ol></CardContent></Card>)}<Card><CardHeader><CardTitle>Voiceover script</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-muted-foreground">{voiceover.map((line,index)=><p key={line}><strong className="text-foreground">Scene {index+1}:</strong> {line}</p>)}</CardContent></Card></div><div className="space-y-4"><Card><CardHeader><CardTitle>Daily accountant checklist</CardTitle></CardHeader><CardContent><ul className="space-y-2 text-sm">{checklist.map(item=><li key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0"/>{item}</li>)}</ul></CardContent></Card><Card><CardHeader><CardTitle>Common mistakes to avoid</CardTitle></CardHeader><CardContent><ul className="list-disc space-y-2 pl-5 text-sm text-muted-foreground"><li>Entering a purchase invoice under the wrong branch.</li><li>Typing medicine names manually when the catalog has the medicine.</li><li>Skipping batch number or expiry date.</li><li>Recording sales but forgetting related expenses.</li><li>Closing the day without reviewing profit and alerts.</li></ul></CardContent></Card></div></div></div>}
