/**
 * Canonical ID mapping: static dataset IDs → live Appwrite medicines IDs.
 *
 * Generated by: node scripts/map-static-to-live-ids.mjs [--write]
 * Public file:  /data/static-to-live-id-map.json
 *
 * Duplicate trade names are listed in `ambiguous_names` and are NOT resolved
 * by name alone (avoids wrong monograph).
 */

import { normalizeTradeName } from "./catalog-links";

export type CanonicalIdMapFile = {
  version: number;
  generated_at?: string | null;
  static_to_live: Record<string, number>;
  name_to_live: Record<string, number>;
  /** normalized name → multiple live ids (do not auto-pick) */
  ambiguous_names?: Record<string, number[]>;
  stats?: Record<string, number | undefined>;
};

export type CanonicalIdMapStatus =
  | "idle"
  | "loading"
  | "ready"
  | "empty"
  | "error";

let cache: CanonicalIdMapFile | null = null;
let loadPromise: Promise<CanonicalIdMapFile | null> | null = null;
let status: CanonicalIdMapStatus = "idle";
let lastError: string | null = null;

const EMPTY: CanonicalIdMapFile = {
  version: 1,
  static_to_live: {},
  name_to_live: {},
  ambiguous_names: {},
};

function isValidMap(data: unknown): data is CanonicalIdMapFile {
  if (!data || typeof data !== "object") return false;
  const d = data as CanonicalIdMapFile;
  return (
    typeof d.static_to_live === "object" &&
    d.static_to_live !== null &&
    typeof d.name_to_live === "object" &&
    d.name_to_live !== null
  );
}

export function getCanonicalIdMapStatus(): CanonicalIdMapStatus {
  return status;
}

export function getCanonicalIdMapError(): string | null {
  return lastError;
}

export async function loadCanonicalIdMap(): Promise<CanonicalIdMapFile> {
  if (cache && status === "ready") return cache;
  if (loadPromise) {
    const m = await loadPromise;
    return m || EMPTY;
  }

  status = "loading";
  lastError = null;

  loadPromise = (async () => {
    try {
      const res = await fetch("/data/static-to-live-id-map.json", {
        cache: "force-cache",
      });
      if (!res.ok) {
        lastError = `Map HTTP ${res.status}`;
        status = "error";
        return EMPTY;
      }
      let data: unknown;
      try {
        data = await res.json();
      } catch {
        lastError = "Map JSON parse failed";
        status = "error";
        return EMPTY;
      }
      if (!isValidMap(data)) {
        lastError = "Map schema invalid";
        status = "error";
        return EMPTY;
      }

      cache = {
        version: data.version || 1,
        generated_at: data.generated_at,
        static_to_live: data.static_to_live || {},
        name_to_live: data.name_to_live || {},
        ambiguous_names: data.ambiguous_names || {},
        stats: data.stats,
      };

      const mapped = Object.keys(cache.static_to_live).length;
      status = mapped > 0 ? "ready" : "empty";
      return cache;
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err);
      status = "error";
      console.warn("[canonical-id-map]", lastError);
      return EMPTY;
    } finally {
      if (status === "error" || status === "empty") {
        loadPromise = null;
      }
    }
  })();

  return (await loadPromise) || EMPTY;
}

export function isAmbiguousName(name: string | null | undefined): boolean {
  if (!cache?.ambiguous_names || !name) return false;
  const key = normalizeTradeName(name);
  return Boolean(key && cache.ambiguous_names[key]?.length);
}

export function getAmbiguousLiveIds(
  name: string | null | undefined,
): number[] {
  if (!cache?.ambiguous_names || !name) return [];
  const key = normalizeTradeName(name);
  return cache.ambiguous_names[key] || [];
}

/** Sync lookup after loadCanonicalIdMap() has completed at least once. */
export function resolveLiveCanonicalIdSync(options: {
  staticId?: number | string | null;
  nameEn?: string | null;
  nameAr?: string | null;
}): number | null {
  if (!cache) return null;
  const { staticId, nameEn, nameAr } = options;

  try {
    if (staticId != null && String(staticId).trim() !== "") {
      const key = String(staticId);
      const live = cache.static_to_live[key];
      if (live != null && Number.isFinite(Number(live))) return Number(live);
    }

    // Never resolve ambiguous names by name alone
    if (isAmbiguousName(nameEn) || isAmbiguousName(nameAr)) {
      return null;
    }

    const ne = normalizeTradeName(nameEn || "");
    if (ne && cache.name_to_live[ne] != null) {
      const id = Number(cache.name_to_live[ne]);
      if (Number.isFinite(id)) return id;
    }
    const na = normalizeTradeName(nameAr || "");
    if (na && cache.name_to_live[na] != null) {
      const id = Number(cache.name_to_live[na]);
      if (Number.isFinite(id)) return id;
    }
  } catch (err) {
    console.warn("[canonical-id-map] resolve error", err);
  }

  return null;
}

export async function resolveLiveCanonicalId(options: {
  staticId?: number | string | null;
  nameEn?: string | null;
  nameAr?: string | null;
}): Promise<number | null> {
  try {
    await loadCanonicalIdMap();
    return resolveLiveCanonicalIdSync(options);
  } catch (err) {
    console.warn("[canonical-id-map] async resolve failed", err);
    return null;
  }
}

export function prefetchCanonicalIdMap(): void {
  void loadCanonicalIdMap().catch((err) => {
    console.warn("[canonical-id-map] prefetch failed", err);
  });
}
