/**
 * Canonical ID mapping: static dataset IDs → live Appwrite medicines IDs.
 *
 * Generated by: node scripts/map-static-to-live-ids.mjs --write
 * Public file:  /data/static-to-live-id-map.json
 *
 * Until the map is generated, resolveLiveCanonicalId falls back to null and
 * encyclopediaProductUrl uses name-keyed links (/catalog/n~NAME).
 */

import { normalizeTradeName } from "./catalog-links";

export type CanonicalIdMapFile = {
  version: number;
  generated_at?: string;
  /** static/legacy id → live Appwrite canonical_id */
  static_to_live: Record<string, number>;
  /** normalized name_en → live Appwrite canonical_id */
  name_to_live: Record<string, number>;
  stats?: {
    mapped?: number;
    names?: number;
  };
};

let cache: CanonicalIdMapFile | null = null;
let loadPromise: Promise<CanonicalIdMapFile | null> | null = null;

const EMPTY: CanonicalIdMapFile = {
  version: 1,
  static_to_live: {},
  name_to_live: {},
};

export async function loadCanonicalIdMap(): Promise<CanonicalIdMapFile> {
  if (cache) return cache;
  if (loadPromise) {
    const m = await loadPromise;
    return m || EMPTY;
  }

  loadPromise = (async () => {
    try {
      const res = await fetch("/data/static-to-live-id-map.json", {
        cache: "force-cache",
      });
      if (!res.ok) return EMPTY;
      const data = (await res.json()) as CanonicalIdMapFile;
      if (!data || typeof data !== "object") return EMPTY;
      cache = {
        version: data.version || 1,
        generated_at: data.generated_at,
        static_to_live: data.static_to_live || {},
        name_to_live: data.name_to_live || {},
        stats: data.stats,
      };
      return cache;
    } catch {
      return EMPTY;
    } finally {
      // allow retry if empty
      if (!cache || Object.keys(cache.static_to_live).length === 0) {
        loadPromise = null;
      }
    }
  })();

  return (await loadPromise) || EMPTY;
}

/** Sync lookup after loadCanonicalIdMap() has completed at least once. */
export function resolveLiveCanonicalIdSync(options: {
  staticId?: number | string | null;
  nameEn?: string | null;
  nameAr?: string | null;
}): number | null {
  if (!cache) return null;
  const { staticId, nameEn, nameAr } = options;

  if (staticId != null && String(staticId).trim() !== "") {
    const key = String(staticId);
    const live = cache.static_to_live[key];
    if (live != null && Number.isFinite(Number(live))) return Number(live);
  }

  const ne = normalizeTradeName(nameEn || "");
  if (ne && cache.name_to_live[ne] != null) {
    return Number(cache.name_to_live[ne]);
  }
  const na = normalizeTradeName(nameAr || "");
  if (na && cache.name_to_live[na] != null) {
    return Number(cache.name_to_live[na]);
  }

  return null;
}

export async function resolveLiveCanonicalId(options: {
  staticId?: number | string | null;
  nameEn?: string | null;
  nameAr?: string | null;
}): Promise<number | null> {
  await loadCanonicalIdMap();
  return resolveLiveCanonicalIdSync(options);
}

/** Prefetch on app shell / encyclopedia mount. */
export function prefetchCanonicalIdMap(): void {
  void loadCanonicalIdMap();
}
