import { serviceRest, stripeClient } from "./_billing-server.js";
import { sendJson, sha256 } from "./_platform-server.js";
export const config={api:{bodyParser:false}};
async function rawBody(request){if(Buffer.isBuffer(request.body))return request.body;if(typeof request.body==="string")return Buffer.from(request.body);const chunks=[];for await(const chunk of request)chunks.push(Buffer.from(chunk));return Buffer.concat(chunks);}
function subscriptionRow(subscription){const userId=subscription.metadata?.user_id||subscription.metadata?.supabase_user_id;const active=["active","trialing"].includes(subscription.status);return userId?{user_id:userId,stripe_customer_id:String(subscription.customer),stripe_subscription_id:subscription.id,stripe_price_id:subscription.items.data[0]?.price?.id||null,subscription_status:subscription.status,subscription_code:active?(subscription.metadata?.subscription_code||"company_subscription"):"none",current_period_end:subscription.current_period_end?new Date(subscription.current_period_end*1000).toISOString():null,cancel_at_period_end:Boolean(subscription.cancel_at_period_end),updated_at:new Date().toISOString()}:null;}
async function updateRequest(id,body){if(id)await serviceRest(`/rest/v1/platform_payment_requests?id=eq.${id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({...body,updated_at:new Date().toISOString()})});}
export default async function handler(request,response){if(request.method!=="POST")return sendJson(response,405,{message:"Method not allowed."});let event;try{const secret=String(process.env.STRIPE_WEBHOOK_SECRET||"");if(!secret)throw new Error("Webhook secret is unavailable.");const raw=await rawBody(request);event=stripeClient().webhooks.constructEvent(raw,String(request.headers["stripe-signature"]||""),secret);const seen=await serviceRest(`/rest/v1/stripe_webhook_events?select=stripe_event_id&stripe_event_id=eq.${event.id}&limit=1`);if(seen?.length)return sendJson(response,200,{received:true,duplicate:true});await serviceRest("/rest/v1/stripe_webhook_events",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({stripe_event_id:event.id,event_type:event.type,livemode:event.livemode,payload_sha256:sha256(raw)})});
    if(["checkout.session.completed","checkout.session.async_payment_succeeded"].includes(event.type)){const session=event.data.object;const requestId=session.metadata?.payment_request_id;await serviceRest(`/rest/v1/platform_payment_transactions?stripe_checkout_session_id=eq.${session.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({stripe_payment_intent_id:typeof session.payment_intent==="string"?session.payment_intent:null,stripe_subscription_id:typeof session.subscription==="string"?session.subscription:null,amount_minor:session.amount_total,currency:session.currency,payment_status:"paid",paid_at:new Date().toISOString(),updated_at:new Date().toISOString()})});await updateRequest(requestId,{status:"paid"});}
    else if(["checkout.session.expired","checkout.session.async_payment_failed"].includes(event.type)){const session=event.data.object;await updateRequest(session.metadata?.payment_request_id,{status:event.type.endsWith("expired")?"expired":"failed"});}
    else if(["customer.subscription.created","customer.subscription.updated","customer.subscription.deleted"].includes(event.type)){const row=subscriptionRow(event.data.object);if(row)await serviceRest("/rest/v1/user_billing_accounts?on_conflict=user_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(row)});}
    await serviceRest(`/rest/v1/stripe_webhook_events?stripe_event_id=eq.${event.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({processing_status:"processed",processed_at:new Date().toISOString()})});return sendJson(response,200,{received:true});
  }catch(error){if(event?.id)await serviceRest(`/rest/v1/stripe_webhook_events?stripe_event_id=eq.${event.id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({processing_status:"failed",error_message:String(error.message||"Processing failed").slice(0,500)})}).catch(()=>undefined);return sendJson(response,400,{message:"Invalid webhook."});}}
